config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get "about-us", to: "about#index", as: :about
  
  # SHEET PAGE
  get "sheet" => "sheet#index"
  post "sheet" => "sheet#index"

  get "sheets" => "sheets#all"

  # RACES PAGE
  get "races" => "races#all"

  # PATHS PAGE
  get "paths" => "paths#all"

  # MAP PAGE
  get "maps" => "maps#all"

  # PLACES PAGE
  get "places" => "places#all"

  # AUTHENTICATION PROCESS
  get "password" => "password#edit", as: :edit_password
  patch "password" => "password#update"

  get "sign_up" => "registration#new"
  post "sign_up" => "registration#create"

  get "sign_in" => "sessions#new"
  post "sign_in" => "sessions#create"
  
  delete "logout" => "sessions#destroy"

  get "password/reset" => "passwords_resets#new"
  post "password/reset" => "passwords_resets#create"

  get "password/reset/edit" => "passwords_resets#edit"
  patch "password/reset/edit" => "passwords_resets#update"
  

# MAIN PAGE
  root to: "main#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
# email:string
# password_digest:string
#
# password:string virtual
# password_confirmation:string virtual

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_secure_password
    validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "Must be a valid email address."}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be logged in to do that" if Current.user.nil?
    end
end
 

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        if session[:user_id]
            @user = User.find_by(id: session[:user_id])
        end
    end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController

    before_action :require_user_logged_in!

    def edit
    end

    def update
       if  Current.user.update(password_params)
        redirect_to root_path, notice: "Password updated."
       else
        render :edit
       end
    end

    private

    def password_params 
        params.require(:user).permit(:password, :password_confirmation)
    end

end

app/controllers/passwords_resets_controller.rb
class PasswordsResetsController < ApplicationController
    def new
        
    end

    def create
        @user = User.find_by(email: params[:email])

        if @user.present?
            PasswordMailer.with(user: @user).reset.deliver_now
        end

        redirect_to root_path, notice: "If an account was found, we have sent a link to change your password."

    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Your token has expired or is invalid, please try again."

    end

    def update
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(password_params)
            redirect_to sign_in_path, notice: "Your password was reset succesfully. Please sign in."
        else
            render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end


end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
end

app/controllers/races_controller.rb
class RacesController < ApplicationController

    def all 
        @angelo_traits = 0
    end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Successfuly created your account!"
        else
            render :new
        end
    end 

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:email])
        
            if user.present? && user.authenticate(params[:password])
                session[:user_id] = user.id
                redirect_to root_path, notice: "Logged in successfully"
            else
                flash[:alert] = "Invalid email or password"
                render :new
            end
    end


    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/controllers/sheet_controller.rb
class SheetController < ApplicationController
    # before_action :require_user_logged_in!
    def index

        # NAME

        @name = params[:name]

        # RACES
        @race = params[:race]



        #  LEVEL

        @level = params[:level]

        # PROFICIENCY

        @proficiency_bonus = 1 + (@level.to_f / 4).ceil || 2

        # ATTRIBUTES

        @strength = params[:strength] || 8
        @mod_strength = (@strength.to_i - 10) / 2

        @dexterity = params[:dexterity] || 8
        @mod_dexterity = (@dexterity.to_i - 10) / 2

        @constitution = params[:constitution] || 8
        @mod_constitution = (@constitution.to_i - 10) / 2
        
        @intelligence = params[:intelligence] || 8
        @mod_intelligence = (@intelligence.to_i - 10) / 2

        @wisdom = params[:wisdom] || 8
        @mod_wisdom = (@wisdom.to_i - 10) / 2

        @charisma = params[:charisma] || 8
        @mod_charisma = (@charisma.to_i - 10) / 2

        # SKILLS

        @athletics = @mod_strength + @proficiency_bonus
        @acrobatics = @mod_dexterity + @proficiency_bonus
        
    end

    def new
        @sheet = Sheet.new
    end

    def create 
        @sheet = Sheet.create(sheet_params)
        if @sheet.save
            session[:sheet_id] = @sheet.id
            redirect_to sheets_path, notice: "Successfuly created your Character Sheet!"
        else
            render :new
        end
    end

    def sheet_params
        params.require(:sheet).permit(:name, :race, :level, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma)
    end
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>SheetMaker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render partial: "shared/navbar" %>

    <div class="container">
        <%= render partial: "shared/flash" %>

        <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        
        <%= yield %>
    </div>
</body>

</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center mt-5">
    <h1>Welcome!<h1>
</div>

<div class="d-flex align-items-center justify-content-center mt-5">
<p>I hope you have fun and find many treasures while you travel within the world of Valantis!</p>
</div>

<% if Current.user %>
Logged in as: <%= Current.user.email %>

<%= button_to "Logout", logout_path, method: :delete %>

<% end %>

app/views/maps/all.html.erb
<div class="d-flex align-items-center justify-content-center mt-5">
    <h1>Maps of Valantis</h1>
</div>
<div class="d-flex align-items-center justify-content-center mt-5">
    <%= image_tag("lucas-toscano-valantis.jpg")%>
</div>

app/views/password/edit.html.erb
<h1>Edit Password</h1>

<%= form_with model: Current.user, url: edit_password_path do |form| %>
    <% if form.objetcs.errors.any? %>
        <div class="alert alert-danger">
            <% form.errors.errors.full_messages.each do |message| %>
                <div><% message %></div>
            <% end %>
        </div>
    <% end %>

    <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", placeholder: "Password" %>
    </div>

    <div class="mb-3">
        <%= form.label :confirm_password %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Password" %>
    </div>

    <div class="mb-3">
        <%= form.submit "Update password", class: "btn btn-primary" %>
    </div>

<% end %>

app/views/passwords_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
    <% if form.object.errors.any? %>
        <div class="alert alert-danger">
        <% form.object.errors.full_messages.each do |message| %>
            <div> <%= message %> </div>
        <% end %>
        </div>
    <% end %>

<div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control", placeholder: "password" %>
</div>

<div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
</div>

<div class="mb-3">
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
</div>
<% end %>

app/views/passwords_resets/new.html.erb
<h1>Forgot your password</h1>

<%= form_with url: password_reset_path do |form| %>
<div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", placeholder: "email@user.com" %>
</div>

<div class="mb-3">
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
</div>
<% end %>

app/views/places/all.html.erb
<h1>All da places bruh</h1>

app/views/races/all.html.erb
<div class="d-flex align-items-center mb-5 mt-5">
    <h1>Races of Valantis</h1>
</div>

<div class="container">
    <h2>Oracles</h2>
    <ul>
        <li>Visions of the Future</li>
    </ul>
    <h2>Angelos</h2>
    <ul>
        <li>Memory from an old time</li>
    </ul>
    <h2>Ice Dwarfs</h2>
        <li></li>
        <li></li>
        <li></li>
    <h2>Mermaids</h2>
        <li></li>
        <li></li>
        <li></li>
    <h2>Humans</h2>
    <li></li>
    <li></li>
    <li></li>
    <h2>Titans</h2>
    <li></li>
    <li></li>
    <li></li>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>

<div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-danger mt-4" role="alert">
    <%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">

        <%= link_to "SheetMaker", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to "Home", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Sheets", sheet_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "My Sheets", sheets_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Races", races_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Paths", paths_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Maps", maps_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Places", places_path, class: "nav-link" %>
                </li>
            </ul>

            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <% if Current.user %>
                <li class="nav-item">
                    <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
                </li>
                <% else %>
                <li class="nav-item">
                    <%= link_to "Login", sign_in_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
                </li>
                <% end %>
            </ul>

        </div>
    </div>
</nav>

app/views/sheet/index.html.erb
<div class="d-flex align-items-center justify-content-center mt-5">
    <h1>Create your sheet!</h1>
</div>

<%= form_with model: @sheet, url: sheet_path do |form| %>

<div class="mb-3 mt-3">
    <h2>Who are you?</h2>
    <%= form.text_field :name, placeholder: "Character name" %>
    <%= @name %>
</div>

<div class="mb-3 mt-3">
    <h3>What is your lineage?</h3>
    <%= form.select :race, options_for_select(["Angelo", "Ice Dwarf", "Oracle", " Mermaid", "Human", "Titan"], @race) %>
</div>

<div class="mb-3 mt-3">
    <h3>Character Level</h3>
    <%= form.select :level, options_for_select(1..20, @level) %>
</div>

<div class="mb-3 mt-3">
    <h3>Proficiency Bonus</h3>
    <%= "+#{@proficiency_bonus}" %>
</div>

<h3>Attributes</h3>

<div class="mb-3">
    <%= form.label :strength %>
    <%= form.select :strength, options_for_select(8..18, @strength) %>
    <%= "Modifier: #{@mod_strength}" %>
</div>

<div class="mb-3">
    <%= form.label :dexterity %>
    <%= form.select :dexterity, options_for_select(8..18, @dexterity) %>
    <%= "Modifier: #{@mod_dexterity}" %>
</div>


<div class="mb-3">
    <%= form.label :constitution %>
    <%= form.select :constitution, options_for_select(8..18, @constitution) %>
    <%= "Modifier: #{@mod_constitution}" %>
</div>

<div class="mb-3">
    <%= form.label :intelligence %>
    <%= form.select :intelligence, options_for_select(8..18, @intelligence) %>
    <%= "Modifier: #{@mod_intelligence}" %>
</div>

<div class="mb-3">
    <%= form.label :wisdom %>
    <%= form.select :wisdom, options_for_select(8..18, @wisdom) %>
    <%= "Modifier: #{@mod_wisdom}" %>
</div>

<div class="mb-3">
    <%= form.label :charisma %>
    <%= form.select :charisma, options_for_select(8..18, @charisma) %>
    <%= "Modifier: #{@mod_charisma}" %>
</div>

<div class="mb-5 mt-5">
    <h3>Skills</h3>
    <%= check_box_tag(:athletics) %>
    <%= label_tag(:athletics, "Athletics")%>
    <%= @athletics %><br>
    <%= check_box_tag(:acrobatics) %>
    <%= label_tag(:acrobatics, "Acrobatics")%>
    <%= @acrobatics %>
</div>

<div class="mb-3">
    <%= form.submit "Create sheet", class: "btn btn-primary" %>
</div>

<% end %>

app/views/sheets/all.html.erb
<h1>hellou</h1>